namespace RestMan.Context.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class ContextFixes : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.MenuItems", "Category_Id", "dbo.Categories");
            DropForeignKey("dbo.Tables", "Hall_Id", "dbo.Halls");
            DropForeignKey("dbo.Orders", "Waiter_Id", "dbo.Users");
            DropForeignKey("dbo.OrderMenuItems", "MenuItem_Id", "dbo.MenuItems");
            DropForeignKey("dbo.Categories", "ShopId", "dbo.Shops");
            DropForeignKey("dbo.Orders", "TableId", "dbo.Tables");
            DropForeignKey("dbo.OrderMenuItems", "OrderId", "dbo.Orders");
            DropForeignKey("dbo.Orders", "ShiftId", "dbo.Shifts");
            DropForeignKey("dbo.Users", "RoleId", "dbo.Roles");
            DropIndex("dbo.Categories", new[] { "ShopId" });
            DropIndex("dbo.MenuItems", new[] { "Category_Id" });
            DropIndex("dbo.Tables", new[] { "Hall_Id" });
            DropIndex("dbo.Orders", new[] { "TableId" });
            DropIndex("dbo.Orders", new[] { "ShiftId" });
            DropIndex("dbo.Orders", new[] { "Waiter_Id" });
            DropIndex("dbo.Users", new[] { "RoleId" });
            DropIndex("dbo.OrderMenuItems", new[] { "OrderId" });
            DropIndex("dbo.OrderMenuItems", new[] { "MenuItem_Id" });
            DropColumn("dbo.MenuItems", "CategoryId");
            DropColumn("dbo.Tables", "HallId");
            DropColumn("dbo.Orders", "WaiterId");
            DropColumn("dbo.OrderMenuItems", "MenuItemId");
            RenameColumn(table: "dbo.MenuItems", name: "Category_Id", newName: "CategoryId");
            RenameColumn(table: "dbo.Tables", name: "Hall_Id", newName: "HallId");
            RenameColumn(table: "dbo.Orders", name: "Waiter_Id", newName: "WaiterId");
            RenameColumn(table: "dbo.OrderMenuItems", name: "MenuItem_Id", newName: "MenuItemId");
            DropPrimaryKey("dbo.Shops");
            DropPrimaryKey("dbo.Tables");
            DropPrimaryKey("dbo.Orders");
            DropPrimaryKey("dbo.Shifts");
            DropPrimaryKey("dbo.Roles");
            DropPrimaryKey("dbo.OrderMenuItems");
            AlterColumn("dbo.Categories", "ShopId", c => c.Long(nullable: false));
            AlterColumn("dbo.MenuItems", "CategoryId", c => c.Long(nullable: false));
            AlterColumn("dbo.MenuItems", "CategoryId", c => c.Long(nullable: false));
            AlterColumn("dbo.Shops", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Tables", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Tables", "HallId", c => c.Long(nullable: false));
            AlterColumn("dbo.Tables", "HallId", c => c.Long(nullable: false));
            AlterColumn("dbo.Orders", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Orders", "WaiterId", c => c.Long(nullable: false));
            AlterColumn("dbo.Orders", "TableId", c => c.Long(nullable: false));
            AlterColumn("dbo.Orders", "ShiftId", c => c.Long(nullable: false));
            AlterColumn("dbo.Orders", "WaiterId", c => c.Long(nullable: false));
            AlterColumn("dbo.Shifts", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Users", "RoleId", c => c.Long(nullable: false));
            AlterColumn("dbo.Roles", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.OrderMenuItems", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.OrderMenuItems", "OrderId", c => c.Long(nullable: false));
            AlterColumn("dbo.OrderMenuItems", "MenuItemId", c => c.Long(nullable: false));
            AlterColumn("dbo.OrderMenuItems", "MenuItemId", c => c.Long(nullable: false));
            AddPrimaryKey("dbo.Shops", "Id");
            AddPrimaryKey("dbo.Tables", "Id");
            AddPrimaryKey("dbo.Orders", "Id");
            AddPrimaryKey("dbo.Shifts", "Id");
            AddPrimaryKey("dbo.Roles", "Id");
            AddPrimaryKey("dbo.OrderMenuItems", "Id");
            CreateIndex("dbo.Categories", "ShopId");
            CreateIndex("dbo.MenuItems", "CategoryId");
            CreateIndex("dbo.Tables", "HallId");
            CreateIndex("dbo.Orders", "WaiterId");
            CreateIndex("dbo.Orders", "TableId");
            CreateIndex("dbo.Orders", "ShiftId");
            CreateIndex("dbo.Users", "RoleId");
            CreateIndex("dbo.OrderMenuItems", "OrderId");
            CreateIndex("dbo.OrderMenuItems", "MenuItemId");
            AddForeignKey("dbo.MenuItems", "CategoryId", "dbo.Categories", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tables", "HallId", "dbo.Halls", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "WaiterId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderMenuItems", "MenuItemId", "dbo.MenuItems", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Categories", "ShopId", "dbo.Shops", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "TableId", "dbo.Tables", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderMenuItems", "OrderId", "dbo.Orders", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "ShiftId", "dbo.Shifts", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Users", "RoleId", "dbo.Roles", "Id", cascadeDelete: true);
        }

        public override void Down()
        {
            DropForeignKey("dbo.Users", "RoleId", "dbo.Roles");
            DropForeignKey("dbo.Orders", "ShiftId", "dbo.Shifts");
            DropForeignKey("dbo.OrderMenuItems", "OrderId", "dbo.Orders");
            DropForeignKey("dbo.Orders", "TableId", "dbo.Tables");
            DropForeignKey("dbo.Categories", "ShopId", "dbo.Shops");
            DropForeignKey("dbo.OrderMenuItems", "MenuItemId", "dbo.MenuItems");
            DropForeignKey("dbo.Orders", "WaiterId", "dbo.Users");
            DropForeignKey("dbo.Tables", "HallId", "dbo.Halls");
            DropForeignKey("dbo.MenuItems", "CategoryId", "dbo.Categories");
            DropIndex("dbo.OrderMenuItems", new[] { "MenuItemId" });
            DropIndex("dbo.OrderMenuItems", new[] { "OrderId" });
            DropIndex("dbo.Users", new[] { "RoleId" });
            DropIndex("dbo.Orders", new[] { "ShiftId" });
            DropIndex("dbo.Orders", new[] { "TableId" });
            DropIndex("dbo.Orders", new[] { "WaiterId" });
            DropIndex("dbo.Tables", new[] { "HallId" });
            DropIndex("dbo.MenuItems", new[] { "CategoryId" });
            DropIndex("dbo.Categories", new[] { "ShopId" });
            DropPrimaryKey("dbo.OrderMenuItems");
            DropPrimaryKey("dbo.Roles");
            DropPrimaryKey("dbo.Shifts");
            DropPrimaryKey("dbo.Orders");
            DropPrimaryKey("dbo.Tables");
            DropPrimaryKey("dbo.Shops");
            AlterColumn("dbo.OrderMenuItems", "MenuItemId", c => c.Long());
            AlterColumn("dbo.OrderMenuItems", "MenuItemId", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderMenuItems", "OrderId", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderMenuItems", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Roles", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Users", "RoleId", c => c.Int(nullable: false));
            AlterColumn("dbo.Shifts", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Orders", "WaiterId", c => c.Long());
            AlterColumn("dbo.Orders", "ShiftId", c => c.Int(nullable: false));
            AlterColumn("dbo.Orders", "TableId", c => c.Int(nullable: false));
            AlterColumn("dbo.Orders", "WaiterId", c => c.Int(nullable: false));
            AlterColumn("dbo.Orders", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Tables", "HallId", c => c.Long());
            AlterColumn("dbo.Tables", "HallId", c => c.Int(nullable: false));
            AlterColumn("dbo.Tables", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Shops", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.MenuItems", "CategoryId", c => c.Long());
            AlterColumn("dbo.MenuItems", "CategoryId", c => c.Int(nullable: false));
            AlterColumn("dbo.Categories", "ShopId", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.OrderMenuItems", "Id");
            AddPrimaryKey("dbo.Roles", "Id");
            AddPrimaryKey("dbo.Shifts", "Id");
            AddPrimaryKey("dbo.Orders", "Id");
            AddPrimaryKey("dbo.Tables", "Id");
            AddPrimaryKey("dbo.Shops", "Id");
            RenameColumn(table: "dbo.OrderMenuItems", name: "MenuItemId", newName: "MenuItem_Id");
            RenameColumn(table: "dbo.Orders", name: "WaiterId", newName: "Waiter_Id");
            RenameColumn(table: "dbo.Tables", name: "HallId", newName: "Hall_Id");
            RenameColumn(table: "dbo.MenuItems", name: "CategoryId", newName: "Category_Id");
            AddColumn("dbo.OrderMenuItems", "MenuItemId", c => c.Int(nullable: false));
            AddColumn("dbo.Orders", "WaiterId", c => c.Int(nullable: false));
            AddColumn("dbo.Tables", "HallId", c => c.Int(nullable: false));
            AddColumn("dbo.MenuItems", "CategoryId", c => c.Int(nullable: false));
            CreateIndex("dbo.OrderMenuItems", "MenuItem_Id");
            CreateIndex("dbo.OrderMenuItems", "OrderId");
            CreateIndex("dbo.Users", "RoleId");
            CreateIndex("dbo.Orders", "Waiter_Id");
            CreateIndex("dbo.Orders", "ShiftId");
            CreateIndex("dbo.Orders", "TableId");
            CreateIndex("dbo.Tables", "Hall_Id");
            CreateIndex("dbo.MenuItems", "Category_Id");
            CreateIndex("dbo.Categories", "ShopId");
            AddForeignKey("dbo.Users", "RoleId", "dbo.Roles", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "ShiftId", "dbo.Shifts", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderMenuItems", "OrderId", "dbo.Orders", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "TableId", "dbo.Tables", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Categories", "ShopId", "dbo.Shops", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderMenuItems", "MenuItem_Id", "dbo.MenuItems", "Id");
            AddForeignKey("dbo.Orders", "Waiter_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Tables", "Hall_Id", "dbo.Halls", "Id");
            AddForeignKey("dbo.MenuItems", "Category_Id", "dbo.Categories", "Id");
        }
    }
}
