// <auto-generated />
namespace RestMan.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OrderChangeAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderChangeAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202405300802555_OrderChangeAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
